name: mraa
description: A Dart FFI wrapper implementation of the Intel linux MRAA device library
version: 1.2.0
homepage: https://github.com/shamblett/mraa

environment:
 sdk: ">=2.6.0  <3.0.0"

dependencies:
 ffi: '^0.1.3'

dev_dependencies:
 test: "^1.14.2"
 pana: "^0.13.5"
 pedantic: "^1.9.0"
 

