name: mraa
description: A Dart FFI wrapper implementation of the Intel linux MRAA device library
version: 2.0.0
homepage: https://github.com/shamblett/mraa

environment:
 sdk: ">=2.12.0  <3.0.0"

dependencies:
 ffi: '^1.0.0'

dev_dependencies:
 test: '^1.14.2'
 pedantic: '^1.9.0'
 

