name: mraa
description: A Dart implementation of the linux mraa device io library
version: 1.0.0
author: Steve Hamblett <steve.hamblett@linux.com>
homepage: https://github.com/shamblett/mraa

environment:
 sdk: ">=2.6.0-dev  <3.0.0"

dependencies:
 ffi: '^0.1.3-dev.3'

dev_dependencies:
 test: '^1.9.3'
 

