name: mraa
description: A Dart FFI wrapper implementation of the Intel linux MRAA device library
version: 2.1.0
homepage: https://github.com/shamblett/mraa

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: ">=2.17.0  <3.0.0"

dependencies:
 ffi: '^2.0.1'
 path: '^1.8.2'

dev_dependencies:
 test: '^1.22.0'
 lints: '^2.0.1'
 

