name: mraa
description: A Dart FFI wrapper implementation of the Intel linux MRAA device library
version: 1.3.1
homepage: https://github.com/shamblett/mraa

environment:
 sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
 ffi: '^0.2.0-nullsafety.1'

dev_dependencies:
 test: "^1.16.0-nullsafety.16"
 pana: "^0.14.10"
 pedantic: "^1.10.0-nullsafety.3"
 

