name: mraa
description: A Dart FFI wrapper implementation of the Intel linux MRAA device library
version: 1.1.1
homepage: https://github.com/shamblett/mraa

environment:
 sdk: ">=2.6.0  <3.0.0"

dependencies:
 ffi: '^0.1.3-dev.3'

dev_dependencies:
 test: '^1.9.3'
 

