name: mraa
description: A Dart FFI wrapper implementation of the Intel linux MRAA device library
version: 4.0.3
repository: https://github.com/shamblett/mraa
homepage: https://github.com/shamblett/mraa

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: '>=3.7.0  <4.0.0'

dependencies:
 ffi: '^2.1.4'
 path: '^1.9.1'

dev_dependencies:
 test: '^1.26.1'
 lints: '^6.0.0'
 ffigen: '^19.0.0'
 dart_code_metrics_presets: '^2.22.0'
 

