name: mraa
description: A Dart FFI wrapper implementation of the Intel linux MRAA device library
version: 4.0.1
repository: https://github.com/shamblett/mraa
homepage: https://github.com/shamblett/mraa

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: '>=3.0.0  <4.0.0'

dependencies:
 ffi: '^2.0.2'
 path: '^1.8.3'

dev_dependencies:
 test: '^1.24.2'
 lints: '^2.1.0'
 ffigen: '^8.0.1'
 

