name: mraa
description: A Dart implementation of the linux mraa device io library
version: 1.0.0
author: Steve Hamblett <steve.hamblett@linux.com>
homepage: https://github.com/shamblett/mraa

environment:
 sdk: ">=2.0.0-dev  <3.0.0"

dependencies:
 

dev_dependencies:
 test: '^1.3.0'
 

