name: Build Status

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test/mraa_aio_test.dart
      - run: dart test/mraa_common_test.dart
      - run: dart test/mraa_gpio_test.dart
      - run: dart test/mraa_i2c_test.dart
      - run: dart test/mraa_led_test.dart
      - run: dart test/mraa_pwm_test.dart
# Issue 13      - run: dart test/mraa_spi_test.dart
      - run: dart test/mraa_uart_test.dart